exceptions = {
        'hiver': 'ivɛr',
        'cher': 'ʃɛr', 
        'mer': 'mɛr', 
        'hier': 'jɛr', 
        'fer': 'fɛr', 
        'ver': 'vɛr',
        'sud': 'syd',
        'femme': 'fam',  
        'gaz': 'gaz',
        'six': 'sis', 
        'dix': 'dis',
        'index': 'ɛ~dɛks', 
        'box': 'bɔks',
        'relax': 'ʁəlaks',
        'complex': 'kɔ~plɛks', 
        'direct': 'dirɛkt',
        'strict': 'strikt', 
        'aspect': 'aspɛ', 
        'respect': 'rɛspɛ',
        'alexander': 'alɛksɑ~dʁ',
        'la': 'la',
        'le': 'lə',
        'les': 'le',
        'une': 'yn',
        'un': 'œ̃',
        'des': 'de',
        'la m': 'la m',
        'maison':'mɛzo~'
    }